version: "3"

services:
  stationdb:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ciclo
      POSTGRES_PASSWORD: ciclo
      POSTGRES_DB: ciclo_dev
    ports:
      - "5433:5432"
    volumes:
      - stationdb_data:/var/lib/postgresql/data
      - ./db/init-queries:/docker-entrypoint-initdb.d

  ciclo-py:
    build:
      context: ./api
      dockerfile: Dockerfile_macos
    volumes:
      - ./api/app:/app
      - ./api/data:/app/data
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      H3_LEVEL: ${H3_LEVEL}
      RADIUS_ACCESS: ${RADIUS_ACCESS}
      HIGH_IMPEDANCE: ${HIGH_IMPEDANCE}
      MEDIUM_IMPEDANCE: ${MEDIUM_IMPEDANCE}
      LOW_IMPEDANCE: ${LOW_IMPEDANCE}
      ELSE_IMPEDANCE: ${ELSE_IMPEDANCE}
    depends_on: 
      - stationdb

volumes:
  stationdb_data:
